  - hosts: database
    tasks:
      - name: Install Mysql
        become: yes #untuk menjadi superuser
        become_user: root
        become_method: su
        apt: name={{ item }} state=latest update_cache=false
        with_items:
          - mysql-server
          - python-mysqldb
      - name: Backup my.cnf
        become: yes
        become_user: root
        become_method: su
        shell: mv /etc/mysql/mariadb.conf.d/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf.bak
      - name: Copy File
        become: yes
        become_user: root
        become_method: su
        copy: src=50-server.cnf dest=/etc/mysql/mariadb.conf.d/
      - name: Restart Mysql
        become: yes
        become_user: root
        become_method: su
        shell: /etc/init.d/mysql restart
      - name: Mysql User
        become: yes
        become_user: root
        become_method: su
        mysql_user:
          login_user: root
          login_password: bolaubi
          name: "{{ item.name }}"
          host: "{{ item.host | default('localhost') }}"
          password: bolaubi
          priv: "*.*:ALL,GRANT"
          #priv: "{{ item.priv | default('*.*:ALL,GRANT') | join('/') }}"
          append_privs: "yes"
        with_items:
          - { name: root, host: 192.168.2.202 }
          - { name: root, host: 192.168.2.196 }
          - { name: root, host: 192.168.2.181 }
          #- { name: root, host: 192.168.43.204, priv: '*.*:ALL,GRANT' }
          #- { name: root, host: 192.168.43.162, priv: '*.*:ALL,GRANT' }
          #- { name: root, host: 192.168.43.220, priv: '*.*:ALL,GRANT' }
      - name: Make DB-Table
        become: yes
        become_user: root
        become_method: su
        mysql_db: name=awanku state=present
